/* eslint-disable */
// CityDB — Sample Dataset (10 cities)
// Full dataset (100 cities): https://damc-979.github.io/citydb
// License: Mystudyglas@proton.me

var CITY_DB = {
    "DE-frankfurt": {
        country: "DE",
        consulate: {
            en: { name: "U.S. Consulate General Frankfurt", address: "Gießener Str. 30, 60435 Frankfurt", tel: "+49 69 7535-0" },
            de: { name: "Amerikanisches Generalkonsulat Frankfurt", address: "Gießener Str. 30, 60435 Frankfurt", tel: "+49 69 7535-0" },
            fr: { name: "Consulat Général des États-Unis Frankfurt", address: "Gießener Str. 30, 60435 Frankfurt", tel: "+49 69 7535-0" },
            hr: { name: "Konzulat Hrvatske u Frankfurtu", address: "Hoffmannstraße 1, 60528 Frankfurt", tel: "+49 69 677-7960" },
            it: { name: "Consolato Generale d'Italia Francoforte", address: "Kettenhofweg 61, 60325 Frankfurt", tel: "+49 69 753-900" },
            es: { name: "Consulado General de España Frankfurt", address: "Nibelungenallee 27, 60318 Frankfurt", tel: "+49 69 959-218-0" },
            hi: { name: "Indian Consulate General Frankfurt", address: "Friedrich-Ebert-Anlage 26, 60325 Frankfurt", tel: "+49 69 1530-050" },
            ar: { name: "القنصلية العامة لمصر في فرانكفورت", address: "Lyoner Str. 15, 60528 Frankfurt", tel: "+49 69 666-2966" },
            zh: { name: "中国驻法兰克福总领事馆", address: "Weißadlergasse 2-4, 60311 Frankfurt", tel: "+49 69 299-8820" },
            ja: { name: "在フランクフルト日本国総領事館", address: "Myliusstr. 34, 60323 Frankfurt", tel: "+49 69 238-1730" },
        },
        hospital: { name: "Universitätsklinikum Frankfurt", address: "Theodor-Stern-Kai 7, 60590 Frankfurt", tel: "+49 69 6301-0" },
        police_main: { name: "Polizeipräsidium Frankfurt", address: "Friedrich-Ebert-Anlage 11, 60327 Frankfurt", tel: "110" },
        airport: { name: "Frankfurt Airport (FRA)", iata: "FRA", distance: "12 km from city center", tel: "+49 180 6 372 4636" },
        bank_exchange: { name: "Deutsche Bank · Commerzbank · Reisebank at FRA", note: "Avoid airport exchange kiosks — rates poor. Use Deutsche Bank ATM." },
        pharmacy_24h: { name: "Apotheke im Hauptbahnhof", address: "Frankfurt Hbf, Level 1", tel: "+49 69 233-047" },
        dentist_24h: { name: "Zahnärztlicher Notfalldienst Frankfurt", tel: "116 117" },
        vet_emergency: { name: "Tierklinik Hofheim (24h)", address: "Katharina-Schlatter-Str. 15, Hofheim", tel: "+49 6192 9960-0" },
        taxi: { number: "069 230001", app: "mytaxi / FREE NOW" },
        car_rental: { name: "Sixt / Europcar / Hertz at FRA Airport and HBF", note: "Book online ahead — cheaper." },
        speed_limits: { urban: "50 km/h", rural: "100 km/h", autobahn: "No limit (advisory 130)" },
        no_go: ["Bahnhofsviertel (red light district) — fine by day, caution at night", "Konstablerwache at night — petty theft"],
        special_zones: ["Frankfurt Innenstadt — Low Emission Zone (Umweltzone), green sticker required", "Sachsenhausen — tourist friendly, busy weekend nights"],

        // IDENTITY & PEOPLE
        mayor: "Mike Josef (SPD)",
        president_country: "Frank-Walter Steinmeier",
        city_hall: { name: "Römer (Rathaus)", address: "Römerberg 23, 60311 Frankfurt", tel: "+49 69 212-0" },
        city_population: 764000,
        happiness_rank: 14, // Germany World Happiness Report 2024
        religion: "Christian 55%, Muslim 10%, No religion 28%, Other 7%",
        greeting: { hello: "Hallo / Guten Tag", thankyou: "Danke schön", goodbye: "Auf Wiedersehen", language: "German" },
        tipping: "Round up or 5-10% in restaurants. Not mandatory but appreciated.",
        restaurant_closing: "Restaurants: 22:00-23:00. Bars/clubs: 03:00-05:00",
        conduct_rules: ["Recycling is serious — use correct bins (Gelber Sack, Altpapier, Restmüll)", "Quiet hours (Ruhezeit): 13:00-15:00 and 22:00-07:00", "Jaywalking frowned upon", "Sunday: most shops closed"],

        // CULTURE & LIFESTYLE
        top_food: ["Grüne Soße (green herb sauce with boiled eggs)", "Handkäse mit Musik (sour milk cheese with onions)", "Frankfurter Würstchen (original)"],
        top_drink: ["Apfelwein (apple wine — Ebbelwoi)", "Hessen beer (Binding, Schöfferhofer)"],
        top_attraction: ["Römerberg (medieval old town)", "Städel Museum", "Palmengarten", "Goethe-Haus", "Sachsenhausen quarter"],
        famous_company: ["Deutsche Bank", "Commerzbank", "Lufthansa HQ", "DWS Group", "European Central Bank"],
        sport_club: "Eintracht Frankfurt (Bundesliga)",
        stadium: "Deutsche Bank Park (capacity 51,500)",
        main_tv: "HR Fernsehen (Hessischer Rundfunk)",
        main_newspaper: "Frankfurter Allgemeine Zeitung (FAZ)",
        main_square: "Römerberg",
        railway_station: { name: "Frankfurt Hauptbahnhof (Hbf)", address: "Am Hauptbahnhof 1" },
        drinking_water: "Tap water is excellent quality. Drink freely.",
        public_transport: "VGF (trams/metro) + S-Bahn. Get 24h ticket at machines.",
        official_holiday: ["New Year", "Good Friday", "Easter Monday", "Labour Day (May 1)", "German Unity Day (Oct 3)", "Christmas (Dec 25-26)"],
        scams: ["Pickpockets at Hauptbahnhof — keep bags in front on platforms and in the station", "Three-card monte at Hauptwache / Zeil — illegal street game, never engage", "Fake taxi touts at airport — use only official Taxi Frankfurt (yellow) from marked ranks", "Gold ring drop — stranger 'finds' a gold ring and offers to sell it to you"],
    },

    "HR-zagreb": {
        country: "HR",
        consulate: {
            en: { name: "U.S. Embassy Zagreb", address: "Ulica Thomasa Jeffersona 2, 10010 Zagreb", tel: "+385 1 661-2200" },
            de: { name: "Deutsche Botschaft Zagreb", address: "Ulica grada Vukovara 64, 10000 Zagreb", tel: "+385 1 630-0100" },
            fr: { name: "Ambassade de France Zagreb", address: "Hebrangova 2, 10000 Zagreb", tel: "+385 1 489-3600" },
            hr: { name: "Ministarstvo vanjskih poslova RH", address: "Trg Nikole Šubića Zrinskog 7-8, 10000 Zagreb", tel: "+385 1 456-9964" },
            it: { name: "Ambasciata d'Italia Zagabria", address: "Medulićeva 22, 10000 Zagreb", tel: "+385 1 489-4200" },
            es: { name: "Embajada de España Zagreb", address: "Tuškanac 21a, 10000 Zagreb", tel: "+385 1 481-7666" },
            hi: { name: "Embassy of India Zagreb", address: "Preradovićeva 21, 10000 Zagreb", tel: "+385 1 487-3269" },
            ar: { name: "سفارة مصر في زغرب", address: "Palmotićeva 28, 10000 Zagreb", tel: "+385 1 461-2680" },
            zh: { name: "中国驻克罗地亚大使馆", address: "Mlinovi 132, 10000 Zagreb", tel: "+385 1 463-2022" },
            ja: { name: "在クロアチア日本国大使館", address: "Miramarska 23, 10000 Zagreb", tel: "+385 1 486-3464" },
        },
        hospital: { name: "KBC Zagreb (University Hospital)", address: "Kišpatićeva 12, 10000 Zagreb", tel: "+385 1 238-8888" },
        police_main: { name: "Policijska uprava zagrebačka", address: "Petrinjska 30, 10000 Zagreb", tel: "192" },
        airport: { name: "Zagreb Airport (ZAG) — Franjo Tuđman", iata: "ZAG", distance: "17 km from city center", tel: "+385 1 626-5222" },
        bank_exchange: { name: "Croatia Banka · Erste Bank · Privredna banka (PBZ)", note: "ATMs widely available. EUR accepted in many places since Croatia joined Eurozone 2023." },
        pharmacy_24h: { name: "Gradska ljekarna Zagreb — Ilica 43", address: "Ilica 43, Zagreb", tel: "+385 1 484-8450" },
        dentist_24h: { name: "Dentalna poliklinika Zagreb", address: "Perkovčeva 3, Zagreb", tel: "+385 1 481-2004" },
        vet_emergency: { name: "Veterinarska stanica Zagreb (24h)", address: "Heinzelova 68, Zagreb", tel: "+385 1 619-3000" },
        taxi: { number: "060 800 800 (Radio Taxi Zagreb)", app: "Uber / Bolt available" },
        car_rental: { name: "Sixt / Budget / Europcar at ZAG Airport", note: "City center also has Hertz." },
        speed_limits: { urban: "50 km/h", rural: "90 km/h", highway: "130 km/h" },
        no_go: ["No major no-go zones — Zagreb is very safe", "Usual caution at night around Kvaternikov trg"],
        special_zones: ["Gornji Grad (Upper Town) — pedestrian area", "Jarun Lake — outdoor recreation zone"],

        mayor: "Tomislav Tomašević (Možemo!)",
        president_country: "Zoran Milanović",
        city_hall: { name: "Gradska skupština Zagreb", address: "Trg Stjepana Radića 1, 10000 Zagreb", tel: "+385 1 610-1000" },
        city_population: 767000,
        happiness_rank: 23,
        religion: "Catholic 86%, Orthodox 4%, Muslim 1%, Other 9%",
        greeting: { hello: "Dobar dan / Bok", thankyou: "Hvala", goodbye: "Doviđenja / Zbogom", language: "Croatian" },
        tipping: "Round up or 10% in restaurants. Not mandatory.",
        restaurant_closing: "Restaurants: 23:00. Cafes: 24:00. Clubs: 04:00-06:00",
        conduct_rules: ["Croatians are warm and hospitable", "Dress modestly when visiting churches", "Tap water is drinkable everywhere in Croatia"],
        top_food: ["Štrukli (cheese pastry)", "Roštilj (grilled meats)", "Fritule (small doughnuts)", "Purica s mlincima (turkey with pasta)"],
        top_drink: ["Rakija (fruit brandy)", "Ožujsko beer", "Karlovačko beer"],
        top_attraction: ["Gornji Grad (Upper Town)", "Cathedral of Zagreb", "Dolac Market", "Museum of Broken Relationships", "Jarun Lake"],
        famous_company: ["Rimac Automobili (electric hypercars)", "Infobip", "Span", "IN2 Group"],
        sport_club: "GNK Dinamo Zagreb (football)",
        stadium: "Stadion Maksimir (capacity 35,123)",
        main_tv: "HRT 1 (Hrvatska radiotelevizija)",
        main_newspaper: "Jutarnji list / Večernji list",
        main_square: "Trg bana Josipa Jelačića",
        railway_station: { name: "Zagreb Glavni kolodvor (Glavni kolodvor)", address: "Trg kralja Tomislava 12" },
        drinking_water: "Excellent. Zagreb tap water is among best in Europe.",
        public_transport: "ZET (trams + buses). Day ticket available at kiosks.",
        official_holiday: ["New Year", "Epiphany (Jan 6)", "Easter", "Labour Day (May 1)", "Corpus Christi", "Statehood Day (Jun 25)", "Homeland Thanksgiving Day (Aug 5)", "Assumption (Aug 15)", "All Saints (Nov 1)", "Christmas (Dec 25-26)"],
        scams: ["Unlicensed taxis — always use Radio Taxi 1717 or Uber", "Overcharging in Old Town restaurants — ask for a printed menu with prices before ordering", "Short-change trick at tourist spots — count your change carefully"],
    },

    "GB-london": {
        country: "GB",
        consulate: {
            en: { name: "Foreign & Commonwealth Office", address: "King Charles Street, London SW1A 2AH", tel: "+44 20 7008-5000" },
            de: { name: "Deutsche Botschaft London", address: "23 Belgrave Square, London SW1X 8PZ", tel: "+44 20 7824-1300" },
            fr: { name: "Ambassade de France Londres", address: "58 Knightsbridge, London SW1X 7JT", tel: "+44 20 7073-1000" },
            hr: { name: "Veleposlanstvo RH u Londonu", address: "21 Conway Street, London W1T 6BN", tel: "+44 20 7387-2022" },
            it: { name: "Ambasciata d'Italia Londra", address: "14 Three Kings Yard, London W1K 4EH", tel: "+44 20 7312-2200" },
            es: { name: "Embajada de España Londres", address: "39 Chesham Place, London SW1X 8SB", tel: "+44 20 7235-5555" },
            hi: { name: "High Commission of India London", address: "India House, Aldwych, London WC2B 4NA", tel: "+44 20 7836-8484" },
            ar: { name: "السفارة المصرية في لندن", address: "26 South Street, London W1K 1DW", tel: "+44 20 7499-3304" },
            zh: { name: "中国驻英国大使馆", address: "49-51 Portland Place, London W1B 1JL", tel: "+44 20 7299-4049" },
            ja: { name: "在英国日本国大使館", address: "101-104 Piccadilly, London W1J 7JT", tel: "+44 20 7465-6500" },
        },
        hospital: { name: "St Thomas' Hospital (NHS)", address: "Westminster Bridge Rd, London SE1 7EH", tel: "+44 20 7188-7188" },
        police_main: { name: "Metropolitan Police HQ", address: "New Scotland Yard, Victoria, London SW1H 0BG", tel: "999 (emergency) / 101 (non-emergency)" },
        airport: { name: "Heathrow Airport (LHR)", iata: "LHR", distance: "24 km from central London", tel: "+44 844 335-1801" },
        bank_exchange: { name: "Barclays · HSBC · NatWest", note: "Use ATMs. Avoid exchange bureaux at airports and tourist spots — terrible rates." },
        pharmacy_24h: { name: "Zafash Pharmacy (24h)", address: "233-235 Old Brompton Rd, London SW5 0EA", tel: "+44 20 7373-2798" },
        dentist_24h: { name: "Dental Emergency Helpline", tel: "111 (NHS)" },
        vet_emergency: { name: "PDSA Animal Hospital (24h)", address: "Various locations", tel: "+44 1923 412410" },
        taxi: { number: "0871 871 8710 (Black Cabs)", app: "Uber / Bolt / FREE NOW" },
        car_rental: { name: "Hertz / Sixt / Enterprise at LHR and city", note: "Left-hand traffic — be careful if not used to it." },
        speed_limits: { urban: "30 mph (48 km/h)", rural: "60 mph (96 km/h)", motorway: "70 mph (112 km/h)" },
        no_go: ["Peckham / Brixton at night — extra caution", "Whitechapel late night", "Anywhere — pickpockets on Tube, especially Central Line"],
        special_zones: ["ULEZ (Ultra Low Emission Zone) — entire Greater London, daily charge for old vehicles", "Congestion Charge Zone — Mon-Fri 07:00-18:00, Sat-Sun 12:00-18:00, £15/day", "Oxford Street — pedestrian priority"],

        mayor: "Sadiq Khan (Labour)",
        president_country: "King Charles III (Monarch) / Keir Starmer (PM)",
        city_hall: { name: "City Hall (London Assembly)", address: "Kamal Chunchie Way, London E16 1ZE", tel: "+44 20 7983-4000" },
        city_population: 9700000,
        happiness_rank: 17,
        religion: "Christian 46%, No religion 37%, Muslim 6%, Hindu 3%, Other 8%",
        greeting: { hello: "Hello / Hi", thankyou: "Thank you / Cheers", goodbye: "Goodbye / Cheers", language: "English" },
        tipping: "10-15% in restaurants. Not obligatory but expected in sit-down service.",
        restaurant_closing: "Restaurants: 23:00. Pubs: 00:00-01:00. Clubs: 03:00-06:00",
        conduct_rules: ["Queue — always, for everything. Jumping queues is deeply offensive", "Stand on the right on escalators — walk on left", "Keep voices low on public transport", "Oyster card or contactless for Tube — cash not accepted"],
        top_food: ["Fish and chips", "Full English breakfast", "Chicken tikka masala (national dish de facto)", "Pie and mash"],
        top_drink: ["Ale / bitter (pub culture)", "Tea — taken seriously", "Gin and tonic"],
        top_attraction: ["Big Ben / Houses of Parliament", "Tower of London", "British Museum", "Tate Modern", "Hyde Park", "Covent Garden"],
        famous_company: ["HSBC", "BP", "Shell", "Vodafone", "Rolls-Royce", "Barclays", "BBC"],
        sport_club: "Arsenal / Chelsea / Tottenham / West Ham (all Premier League)",
        stadium: "Wembley Stadium (capacity 90,000)",
        main_tv: "BBC One / ITV",
        main_newspaper: "The Guardian / The Times / Daily Mail",
        main_square: "Trafalgar Square",
        railway_station: { name: "London Waterloo / King's Cross / Paddington", address: "Multiple major terminals" },
        drinking_water: "Safe and good quality from tap. Slightly hard in London.",
        public_transport: "TfL — Tube, bus, Overground. Use Oyster or contactless. 24h Tube on weekends.",
        official_holiday: ["New Year", "Good Friday", "Easter Monday", "Early May Bank Holiday", "Spring Bank Holiday", "Summer Bank Holiday", "Christmas (Dec 25)", "Boxing Day (Dec 26)"],
        scams: ["Pickpockets on the Tube — especially Central and Jubilee lines at busy stations", "Fake police officers asking to inspect your wallet or passport — real police never do this", "Overpriced cycle rickshaws (pedicabs) near tourist areas — always agree price before riding", "Three-card trick teams at Oxford Street and Covent Garden — illegal, walk away", "Card skimming at standalone ATMs near tourist sites — use bank-branch ATMs only"],
    },

    "FR-paris": {
        country: "FR",
        consulate: {
            en: { name: "U.S. Embassy Paris", address: "2 Avenue Gabriel, 75008 Paris", tel: "+33 1 43-12-22-22" },
            de: { name: "Deutsche Botschaft Paris", address: "13 Avenue Franklin D. Roosevelt, 75008 Paris", tel: "+33 1 53-83-45-00" },
            fr: { name: "Ministère des Affaires étrangères", address: "37 Quai d'Orsay, 75007 Paris", tel: "+33 1 43-17-67-67" },
            hr: { name: "Veleposlanstvo RH u Parizu", address: "39 Boulevard Malesherbes, 75008 Paris", tel: "+33 1 53-04-55-00" },
            it: { name: "Ambasciata d'Italia Parigi", address: "47 Rue de Varenne, 75007 Paris", tel: "+33 1 49-54-03-00" },
            es: { name: "Embajada de España París", address: "22 Avenue Marceau, 75008 Paris", tel: "+33 1 44-43-18-00" },
            hi: { name: "Embassy of India Paris", address: "15 Rue Alfred Dehodencq, 75016 Paris", tel: "+33 1 40-50-70-70" },
            ar: { name: "السفارة المصرية في باريس", address: "56 Avenue d'Iéna, 75116 Paris", tel: "+33 1 53-67-88-30" },
            zh: { name: "中国驻法国大使馆", address: "11 Avenue George V, 75008 Paris", tel: "+33 1 47-23-36-77" },
            ja: { name: "在フランス日本国大使館", address: "7 Avenue Hoche, 75008 Paris", tel: "+33 1 48-88-62-00" },
        },
        hospital: { name: "Hôpital Hôtel-Dieu (AP-HP)", address: "1 Parvis Notre-Dame, 75004 Paris", tel: "+33 1 42-34-82-34" },
        police_main: { name: "Préfecture de Police de Paris", address: "9 Boulevard du Palais, 75004 Paris", tel: "17" },
        airport: { name: "Charles de Gaulle Airport (CDG)", iata: "CDG", distance: "25 km from city center", tel: "+33 1 70-36-39-50" },
        bank_exchange: { name: "BNP Paribas · Société Générale · Crédit Agricole", note: "Use bank ATMs. Change bureaux near Champs-Élysées — very poor rates." },
        pharmacy_24h: { name: "Pharmacie des Champs (24h)", address: "84 Avenue des Champs-Élysées, 75008 Paris", tel: "+33 1 45-62-02-41" },
        dentist_24h: { name: "SOS Dentaire", tel: "+33 1 43-37-51-00" },
        vet_emergency: { name: "ADVETIA Clinique Vétérinaire (24h)", address: "9 Rue Beaubourg, 75004 Paris", tel: "+33 1 71-19-74-74" },
        taxi: { number: "3609 (G7 Taxis)", app: "Uber / Bolt / Heetch" },
        car_rental: { name: "Hertz / Europcar / ADA at CDG and city", note: "Paris traffic is intense. Metro usually faster." },
        speed_limits: { urban: "30 km/h (most streets since 2021)", peripheral: "70 km/h", highway: "130 km/h" },
        no_go: ["Gare du Nord surroundings — pickpockets, scammers", "Barbès-Rochechouart at night", "Bois de Boulogne at night", "Stade de France area at night"],
        special_zones: ["Zone à Faibles Émissions (ZFE) — low emission zone entire Paris", "Paris Plages — summer beach along Seine", "Marais — LGBTQ+ friendly, tourist popular"],

        mayor: "Anne Hidalgo (PS)",
        president_country: "Emmanuel Macron",
        city_hall: { name: "Hôtel de Ville de Paris", address: "Place de l'Hôtel-de-Ville, 75004 Paris", tel: "+33 1 42-76-40-40" },
        city_population: 2200000,
        happiness_rank: 21,
        religion: "Christian 51%, No religion 35%, Muslim 10%, Jewish 1%, Other 3%",
        greeting: { hello: "Bonjour / Bonsoir", thankyou: "Merci / Merci beaucoup", goodbye: "Au revoir / Bonne journée", language: "French" },
        tipping: "Service included by law (15%). Extra tip appreciated but not expected — round up or leave €1-2.",
        restaurant_closing: "Restaurants: 22:30-23:00. Brasseries: 01:00. Clubs: 06:00-08:00",
        conduct_rules: ["Always say Bonjour/Bonsoir when entering a shop — mandatory politeness", "Bread is not ordered — brought automatically", "Do not eat while walking — considered rude", "Dress well — Parisians notice"],
        top_food: ["Croissant (fresh from boulangerie)", "Steak frites", "Croque-monsieur", "Escargots", "Crème brûlée"],
        top_drink: ["Wine (Bordeaux, Burgundy, Champagne)", "Pastis", "Café express"],
        top_attraction: ["Eiffel Tower", "Louvre Museum", "Notre-Dame Cathedral", "Musée d'Orsay", "Sacré-Cœur", "Palace of Versailles (30km)"],
        famous_company: ["Louis Vuitton (LVMH)", "L'Oréal", "Total Energies", "BNP Paribas", "Airbus", "Dior", "Chanel"],
        sport_club: "Paris Saint-Germain (PSG)",
        stadium: "Parc des Princes (capacity 47,929)",
        main_tv: "TF1 / France 2",
        main_newspaper: "Le Monde / Le Figaro / Libération",
        main_square: "Place de la Concorde / Place de la République",
        railway_station: { name: "Gare du Nord / Gare de Lyon / Gare Saint-Lazare", address: "Multiple major terminals" },
        drinking_water: "Safe from tap. Slightly chlorinated taste. Free drinking fountains throughout city.",
        public_transport: "RATP — Métro, RER, bus. Navigo card or t+ tickets. Very extensive network.",
        official_holiday: ["New Year", "Easter Monday", "Labour Day (May 1)", "Victory in Europe Day (May 8)", "Ascension", "Bastille Day (Jul 14)", "Assumption (Aug 15)", "All Saints (Nov 1)", "Armistice Day (Nov 11)", "Christmas"],
        scams: ["Friendship bracelet scam at Sacré-Cœur — vendors forcibly tie a bracelet on your wrist then demand payment", "Gold ring drop scam near Eiffel Tower — 'found' gold ring offered for sale", "Petition clipboard scam — someone asks you to sign a petition then demands money", "Pickpockets on Métro Line 1 and RER B (CDG airport line) — keep bags in front", "Fake airport shuttle drivers at CDG — use only official RATP buses or licensed taxis"],
    },

    "JP-tokyo": {
        country: "JP",
        consulate: {
            en: { name: "U.S. Embassy Tokyo", address: "1-10-5 Akasaka, Minato, Tokyo 107-8420", tel: "+81 3 3224-5000" },
            de: { name: "Deutsche Botschaft Tokio", address: "4-5-10 Minami-Azabu, Minato, Tokyo 106-0047", tel: "+81 3 5791-7700" },
            fr: { name: "Ambassade de France Tokyo", address: "4-11-44 Minami-Azabu, Minato, Tokyo 106-8514", tel: "+81 3 5798-6000" },
            hr: { name: "Embassy of Croatia Tokyo", address: "3-3-10 Hiroo, Shibuya, Tokyo 150-0012", tel: "+81 3 5464-2400" },
            it: { name: "Ambasciata d'Italia Tokyo", address: "2-5-4 Mita, Minato, Tokyo 108-8302", tel: "+81 3 3453-5291" },
            es: { name: "Embajada de España Tokio", address: "1-3-29 Roppongi, Minato, Tokyo 106-0032", tel: "+81 3 3583-8531" },
            hi: { name: "Embassy of India Tokyo", address: "2-2-11 Kudan Minami, Chiyoda, Tokyo 102-0074", tel: "+81 3 3262-2391" },
            ar: { name: "سفارة مصر في طوكيو", address: "1-5-4 Aobadai, Meguro, Tokyo 153-0042", tel: "+81 3 3770-8022" },
            zh: { name: "中国驻日本大使馆", address: "3-4-33 Moto-Azabu, Minato, Tokyo 106-0046", tel: "+81 3 3403-3380" },
            ja: { name: "外務省（在外公館）", address: "2-2-1 Kasumigaseki, Chiyoda, Tokyo 100-8919", tel: "+81 3 3580-3311" },
        },
        hospital: { name: "Tokyo Medical and Surgical Clinic", address: "32 Shiba Koen 3-chome, Minato, Tokyo 105-0011", tel: "+81 3 3436-3028" },
        police_main: { name: "Metropolitan Police Department", address: "2-1-1 Kasumigaseki, Chiyoda, Tokyo 100-8929", tel: "110" },
        airport: { name: "Narita International Airport (NRT)", iata: "NRT", distance: "60 km from city center", tel: "+81 476 34-8000" },
        bank_exchange: { name: "Japan Post Bank · 7-Eleven ATMs · Shinsei Bank", note: "7-Eleven and Japan Post ATMs accept foreign cards. Most places cash only." },
        pharmacy_24h: { name: "Matsumoto Kiyoshi (major chain, many 24h locations)", tel: "Check nearest branch" },
        dentist_24h: { name: "Tokyo Dental Emergency Tel", tel: "+81 3 3263-2389" },
        vet_emergency: { name: "Japan Animal Referral Medical Center (24h)", address: "2-12-24 Yanagishima, Kawasaki", tel: "+81 44 712-0916" },
        taxi: { number: "03-3563-5101 (Nihon Kotsu)", app: "GO app / DiDi" },
        car_rental: { name: "Toyota Rent a Car / Times Car Rental", note: "International license required. Left-hand traffic." },
        speed_limits: { urban: "40-60 km/h", expressway: "80-100 km/h" },
        no_go: ["Tokyo is extremely safe — almost no no-go zones", "Kabukicho (Shinjuku) — entertainment district, minor scam risk at night"],
        special_zones: ["Shibuya — pedestrian scramble crossing (world famous)", "Akihabara — electronics/anime district", "Harajuku — fashion youth culture"],

        mayor: "Yuriko Koike (Governor of Tokyo)",
        president_country: "Emperor Naruhito / PM Fumio Kishida",
        city_hall: { name: "Tokyo Metropolitan Government Building", address: "2-8-1 Nishi-Shinjuku, Shinjuku, Tokyo 163-8001", tel: "+81 3 5321-1111" },
        city_population: 13960000,
        happiness_rank: 47,
        religion: "Shinto + Buddhist 70% (often both), Christian 1%, Other/None 29%",
        greeting: { hello: "Konnichiwa (こんにちは)", thankyou: "Arigatou gozaimasu (ありがとうございます)", goodbye: "Sayonara (さようなら)", language: "Japanese" },
        tipping: "NEVER tip in Japan — considered rude or offensive. Service is always included.",
        restaurant_closing: "Restaurants: 22:00-23:00. Izakayas: 00:00-02:00. Last trains ~01:00.",
        conduct_rules: ["No eating or drinking while walking", "Speak quietly on trains — silent culture", "Two hands when giving or receiving business cards", "Remove shoes when entering homes and many traditional venues", "Cash is king — many places do not accept cards"],
        top_food: ["Sushi / Sashimi", "Ramen", "Tempura", "Yakitori", "Wagyu beef", "Onigiri"],
        top_drink: ["Sake (rice wine)", "Japanese whisky (Suntory, Nikka)", "Matcha", "Asahi/Sapporo/Kirin beer"],
        top_attraction: ["Shibuya crossing", "Senso-ji Temple (Asakusa)", "Shinjuku Gyoen", "teamLab digital art", "Tokyo Skytree", "Harajuku"],
        famous_company: ["Toyota", "Sony", "Honda", "Panasonic", "Mitsubishi", "Softbank", "Uniqlo"],
        sport_club: "FC Tokyo / Urawa Red Diamonds (J-League)",
        stadium: "Japan National Stadium (capacity 68,000)",
        main_tv: "NHK / Fuji TV",
        main_newspaper: "Yomiuri Shimbun / Asahi Shimbun",
        main_square: "Shibuya Scramble / Shinjuku Station area",
        railway_station: { name: "Tokyo Station / Shinjuku Station (busiest in world)", address: "1 Chome-9 Marunouchi, Chiyoda" },
        drinking_water: "Excellent — tap water is among the best in the world. Drink freely.",
        public_transport: "JR East + Tokyo Metro + Toei. IC card (Suica/Pasmo) essential. Extremely punctual.",
        official_holiday: ["New Year (Jan 1-3)", "Coming of Age Day", "National Foundation Day (Feb 11)", "Spring Equinox", "Showa Day (Apr 29)", "Golden Week (late Apr-May 5)", "Marine Day", "Mountain Day", "Respect for Aged Day", "Autumn Equinox", "Health & Sports Day", "Culture Day (Nov 3)", "Labour Day (Nov 23)", "Emperor's Birthday (Feb 23)"],
        scams: ["Tourist trap bars in Roppongi — extremely overpriced drinks and aggressive staff, agree all prices before ordering", "Rigged games near Shinjuku station — 'lucky' draw games are impossible to win", "Taxi overcharge for tourists — always use metered official taxis or apps like GO"],
    },
    
    "AE-dubai": {
        country: "AE",
        consulate: {
            en: { name: "U.S. Consulate General Dubai", address: "Corner of Al Seef Rd and Sheikh Khalifa bin Zayed Rd, Dubai", tel: "+971 4 309-4000" },
            de: { name: "Deutsches Generalkonsulat Dubai", address: "Dubai World Trade Centre, Level 7, Dubai", tel: "+971 4 397-2333" },
            fr: { name: "Consulat Général de France Dubaï", address: "API Trio Tower, Sheikh Zayed Rd, Dubai", tel: "+971 4 408-4900" },
            hr: { name: "Embassy of Croatia Abu Dhabi", address: "Villa No. 9, Al Mutarad Street, Abu Dhabi", tel: "+971 2 672-7770" },
            it: { name: "Consolato Generale d'Italia Dubai", address: "Emaar Square, Bldg 4, Downtown Dubai", tel: "+971 4 331-4167" },
            es: { name: "Embajada de España Abu Dhabi", address: "Villa 8, Al Nahyan St, Abu Dhabi", tel: "+971 2 626-5504" },
            hi: { name: "Indian Consulate General Dubai", address: "Consulate Lane, Oud Metha, Dubai", tel: "+971 4 397-1222" },
            ar: { name: "القنصلية المصرية في دبي", address: "الديرة، دبي", tel: "+971 4 226-4100" },
            zh: { name: "中国驻迪拜总领事馆", address: "World Trade Centre Area, Dubai", tel: "+971 4 394-4733" },
            ja: { name: "在ドバイ日本国総領事館", address: "Dubai World Trade Centre, Level 17", tel: "+971 4 331-9191" },
        },
        hospital: { name: "Rashid Hospital (Government)", address: "Oud Metha, Dubai", tel: "+971 4 219-2000" },
        police_main: { name: "Dubai Police HQ", address: "Dubai Police Academy, Dubai", tel: "999" },
        airport: { name: "Dubai International Airport (DXB)", iata: "DXB", distance: "5 km from Downtown", tel: "+971 4 224-5555" },
        bank_exchange: { name: "Emirates NBD · ADCB · Al Ansari Exchange", note: "Al Ansari and UAE Exchange — good rates for cash. Avoid airport exchange." },
        pharmacy_24h: { name: "Aster Pharmacy (24h — many branches)", tel: "+971 4 440-2222" },
        dentist_24h: { name: "Dr. Rami Dental Clinic (24h)", tel: "+971 4 344-4441" },
        vet_emergency: { name: "British Veterinary Clinic (24h)", address: "Jumeirah, Dubai", tel: "+971 4 344-9773" },
        taxi: { number: "04 208 0808 (Dubai Taxi Corporation)", app: "Uber / Careem" },
        car_rental: { name: "Hertz / Thrifty / Budget at DXB Airport", note: "Easy to drive here. Right-hand traffic. Highways excellent." },
        speed_limits: { urban: "60-80 km/h", highway: "120-140 km/h" },
        no_go: ["Dubai is very safe — extremely low crime", "Avoid public displays of affection — illegal", "Bur Dubai / Deira at night — fine, just busy"],
        special_zones: ["Downtown Dubai / Dubai Marina — tourist hub", "Gold Souk / Spice Souk Deira — old Dubai", "Palm Jumeirah — luxury resort island"],

        mayor: "Sheikh Mohammed bin Rashid Al Maktoum (Ruler of Dubai)",
        president_country: "President of UAE: Sheikh Mohamed bin Zayed Al Nahyan",
        city_hall: { name: "Dubai Municipality", address: "Deira, Dubai", tel: "800 900" },
        city_population: 3604000,
        happiness_rank: 26,
        religion: "Muslim 76% (mostly South Asian workers), Christian 9%, Hindu 10%, Other 5%",
        greeting: { hello: "As-salamu alaykum / Marhaba (مرحبا)", thankyou: "Shukran (شكراً)", goodbye: "Ma'a as-salama (مع السلامة)", language: "Arabic (English widely spoken)" },
        tipping: "10-15% in restaurants. Not mandatory but appreciated.",
        restaurant_closing: "Restaurants: 00:00-01:00. Licensed bars: 03:00. No closing time in malls.",
        conduct_rules: ["No public alcohol (except licensed venues)", "No public displays of affection — fines/arrest possible", "Dress modestly in malls and public areas", "Ramadan: no eating/drinking/smoking in public during daylight hours", "Photography of government buildings, military, airports forbidden"],
        top_food: ["Shawarma", "Al Harees (slow-cooked wheat and meat)", "Manousheh (flatbread)", "Machboos (spiced rice with meat)", "Luqaimat (sweet dumplings)"],
        top_drink: ["Arabic coffee (Qahwa — cardamom coffee)", "Camel milk", "Fresh fruit juices", "Non-alcoholic cocktails"],
        top_attraction: ["Burj Khalifa", "Dubai Mall", "Dubai Creek", "Gold Souk", "Desert Safari", "Palm Jumeirah", "Museum of the Future"],
        famous_company: ["Emirates Airlines", "DP World", "Emaar Properties", "ENOC", "Dubai Ports", "Jumeirah Group"],
        sport_club: "Al Wasl FC / Dubai Exiles Rugby",
        stadium: "Dubai International Cricket Stadium / Al Maktoum Stadium",
        main_tv: "Dubai TV / Al Arabiya",
        main_newspaper: "Gulf News / Khaleej Times / The National",
        main_square: "Dubai Fountain (Downtown) / Deira Gold Souk area",
        railway_station: { name: "Dubai Metro (no intercity train)", address: "Red and Green lines, 49 stations" },
        drinking_water: "Tap water technically safe but most residents drink bottled. Use bottled water.",
        public_transport: "Dubai Metro + RTA Buses. Nol card for contactless. Taxis plentiful and metered.",
        official_holiday: ["New Year", "Eid Al Fitr (3 days — Islamic calendar)", "Eid Al Adha (3 days)", "Islamic New Year", "Prophet's Birthday", "UAE National Day (Dec 2-3)"],
        scams: ["Fake timeshare presentations — promise of free gifts leads to high-pressure property sales", "Unlicensed taxi touts at malls and airport — use Dubai Taxi (RTA), Careem or Uber only", "Counterfeit goods in souks — luxury watches, bags and electronics are often fake", "Photographing people without consent — can result in a legal complaint; always ask permission"],
    },

    
    "US-newyork": {
        country: "US",
        consulate: {
            en: { name: "NYC is the US — contact foreign embassy in DC", address: "Multiple foreign consulates in Midtown Manhattan", tel: "311 (city services)" },
            de: { name: "Deutsches Generalkonsulat New York", address: "871 United Nations Plaza, New York, NY 10017", tel: "+1 212 610-9700" },
            fr: { name: "Consulat Général de France New York", address: "934 Fifth Avenue, New York, NY 10021", tel: "+1 212 606-3600" },
            hr: { name: "Consulate General of Croatia New York", address: "369 Lexington Avenue, Suite 1108, New York, NY 10017", tel: "+1 212 599-3066" },
            it: { name: "Consolato Generale d'Italia New York", address: "690 Park Avenue, New York, NY 10021", tel: "+1 212 737-9100" },
            es: { name: "Consulado General de España New York", address: "150 East 58th Street, New York, NY 10155", tel: "+1 212 355-4080" },
            hi: { name: "Consulate General of India New York", address: "3 East 64th Street, New York, NY 10065", tel: "+1 212 774-0600" },
            ar: { name: "القنصلية المصرية في نيويورك", address: "1110 Second Avenue, New York, NY 10022", tel: "+1 212 759-7120" },
            zh: { name: "中国驻纽约总领事馆", address: "520 12th Avenue, New York, NY 10036", tel: "+1 212 244-9456" },
            ja: { name: "在ニューヨーク日本国総領事館", address: "299 Park Avenue, New York, NY 10171", tel: "+1 212 371-8222" },
        },
        hospital: { name: "NewYork-Presbyterian Hospital", address: "525 East 68th Street, New York, NY 10065", tel: "+1 212 746-5454" },
        police_main: { name: "NYPD 1st Precinct (Manhattan South)", address: "16 Ericsson Place, New York, NY 10013", tel: "911 (emergency) / 311 (non-emergency)" },
        airport: { name: "JFK International Airport", iata: "JFK", distance: "25 km from Midtown", tel: "+1 718 244-4444" },
        bank_exchange: { name: "Chase · Bank of America · Citibank", note: "ATMs everywhere. Travelex at airports — avoid, poor rates. Use bank ATM." },
        pharmacy_24h: { name: "Duane Reade / Walgreens (24h many locations)", tel: "Check nearest branch" },
        dentist_24h: { name: "NYC Dental Emergency", tel: "+1 212 245-5801" },
        vet_emergency: { name: "BluePearl Pet Hospital (24h)", address: "410 West 55th Street, New York, NY 10019", tel: "+1 212 767-0099" },
        taxi: { number: "Hail on street (Yellow/Green cab)", app: "Uber / Lyft / Via" },
        car_rental: { name: "Hertz / Enterprise / Avis at JFK/airports", note: "Do not rent a car to use in Manhattan — parking impossible and expensive." },
        speed_limits: { urban: "25 mph (40 km/h) NYC default since 2014", expressway: "50 mph (80 km/h)" },
        no_go: ["Avoid isolated areas of the Bronx at night", "Parts of East New York (Brooklyn) at night", "Always general vigilance in subway — petty theft"],
        special_zones: ["Times Square — tourist trap, watch belongings", "Central Park — safe during day, caution at night", "Midtown business district Mon-Fri hectic"],

        mayor: "Eric Adams (Democrat)",
        president_country: "Joe Biden / Donald Trump (elected 2024)",
        city_hall: { name: "New York City Hall", address: "City Hall Park, New York, NY 10007", tel: "+1 212 788-3000" },
        city_population: 8336000,
        happiness_rank: 23,
        religion: "Christian 57%, No religion 29%, Jewish 8%, Muslim 3%, Other 3%",
        greeting: { hello: "Hi / Hey / Hello", thankyou: "Thanks / Thank you", goodbye: "Bye / See you", language: "English" },
        tipping: "MANDATORY culture — 18-25% in restaurants, $1-2 per drink at bar, $1-2 per bag at hotel. Not tipping is insulting.",
        restaurant_closing: "Restaurants: 23:00-00:00. Bars: 04:00. Many 24h diners.",
        conduct_rules: ["Tip everywhere — it is part of wages", "Walk fast — slow walkers move to the right", "Personal space respected — don't stand too close", "ID required for bars even if you look 40"],
        top_food: ["NY Pizza (slice)", "Bagel with lox and cream cheese", "Pastrami sandwich (Katz's Deli)", "Hot dog from cart", "Cheesecake"],
        top_drink: ["Craft beer", "Cocktails (NYC bar scene world class)", "Bodega coffee"],
        top_attraction: ["Central Park", "Brooklyn Bridge", "Statue of Liberty", "Times Square", "The Met", "MoMA", "High Line"],
        famous_company: ["Goldman Sachs", "JPMorgan Chase", "Google NY", "Facebook/Meta NY", "Bloomberg", "NYSE"],
        sport_club: "New York Yankees (MLB) / NY Knicks (NBA) / NY Giants (NFL)",
        stadium: "Yankee Stadium / Madison Square Garden",
        main_tv: "NBC / CBS / ABC / NY1",
        main_newspaper: "New York Times / New York Post / Daily News",
        main_square: "Times Square",
        railway_station: { name: "Penn Station / Grand Central Terminal", address: "34th Street / 42nd Street Manhattan" },
        drinking_water: "Excellent — NYC tap water is famous for quality. Drink freely.",
        public_transport: "MTA — Subway + buses. OMNY contactless card tap. Subway runs 24/7.",
        official_holiday: ["New Year", "MLK Day (Jan)", "Presidents Day (Feb)", "Memorial Day (May)", "Independence Day (Jul 4)", "Labor Day (Sep)", "Thanksgiving (Nov)", "Christmas"],
        scams: ["Unlicensed taxis at JFK and Newark — use official yellow cab rank or rideshare apps only", "Three-card monte in Times Square and near subway stations — illegal, never stop", "Fake CD musicians — they hand you a CD as a 'gift' then aggressively demand $20+", "Broken camera con — stranger drops camera near you, claims you broke it and demands money", "Ticket scalpers near MSG and Broadway — buy only from official box offices"],
    },

    "TR-istanbul": {
        country: "TR",
        consulate: {
            en: { name: "U.S. Consulate General Istanbul", address: "İstinye Mahallesi, Üç Şehitler Sokak 2, Sarıyer, Istanbul", tel: "+90 212 335-9000" },
            de: { name: "Deutsches Generalkonsulat Istanbul", address: "İnönü Caddesi 16-18, 34437 Gümüşsuyu, Istanbul", tel: "+90 212 334-6100" },
            fr: { name: "Consulat Général de France Istanbul", address: "İstiklal Caddesi 8, 34435 Beyoğlu, Istanbul", tel: "+90 212 334-8730" },
            hr: { name: "Konzulat Hrvatske u Istanbulu", address: "Sinanpaşa Mah. Şair Nedim Cad. 8, Beşiktaş, Istanbul", tel: "+90 212 260-5086" },
            it: { name: "Consolato Generale d'Italia Istanbul", address: "Tomtom Kaptan Sokak 15, 34433 Beyoğlu, Istanbul", tel: "+90 212 243-1024" },
            es: { name: "Consulado General de España Istanbul", address: "Karanfil Sokak 16, 34365 Şişli, Istanbul", tel: "+90 212 291-1390" },
            hi: { name: "Consulate General of India Istanbul", address: "Cumhuriyet Cad. 10 Şişli, Istanbul", tel: "+90 212 296-2535" },
            ar: { name: "القنصلية المصرية في إسطنبول", address: "Şakayık Sokak 36, Nişantaşı, Istanbul", tel: "+90 212 224-1636" },
            zh: { name: "中国驻伊斯坦布尔总领事馆", address: "Miralay Şefik Bey Sok 4, Gümüşsuyu, Istanbul", tel: "+90 212 251-9994" },
            ja: { name: "在イスタンブール日本国総領事館", address: "İnönü Cad. 24, Gümüşsuyu, Istanbul", tel: "+90 212 317-4600" },
        },
        hospital: { name: "American Hospital Istanbul (Amerikan Hastanesi)", address: "Güzelbahçe Sokak 20, Nişantaşı, Istanbul", tel: "+90 212 444-3777" },
        police_main: { name: "İstanbul Emniyet Müdürlüğü (Police HQ)", address: "Vatan Caddesi, Fatih, Istanbul", tel: "155" },
        airport: { name: "Istanbul Airport (IST)", iata: "IST", distance: "35-45 km from city center", tel: "+90 444 0-165" },
        bank_exchange: { name: "Ziraat Bankası · Garanti BBVA · İş Bankası", note: "Exchange offices (Döviz bürosu) in Grand Bazaar area — competitive rates." },
        pharmacy_24h: { name: "Nöbetçi eczane — rotating 24h pharmacy", note: "Check Google Maps for 'nöbetçi eczane' — changes daily by regulation." },
        dentist_24h: { name: "Istanbul Diş Hastanesi (emergency)", tel: "+90 212 466-3377" },
        vet_emergency: { name: "Istanbul Veteriner Acil (24h)", tel: "+90 212 287-4949" },
        taxi: { number: "Hail on street or call dispatch", app: "BiTaksi / Uber" },
        car_rental: { name: "Sixt / Europcar / Budget at IST Airport and city", note: "Traffic in Istanbul is notoriously bad. Metro or ferry faster." },
        speed_limits: { urban: "50 km/h", interurban: "90 km/h", highway: "120 km/h" },
        no_go: ["Tarlabaşı area (Beyoğlu) at night — some risk", "Avoid unofficial currency exchange on street", "Shoe shiners 'accidentally' dropping brush — tourist scam"],
        special_zones: ["Grand Bazaar — haggling expected, no fixed prices", "Spice Bazaar (Mısır Çarşısı) — tourist crowds", "Bosphorus — divides Europe and Asia"],
        mayor: "Ekrem İmamoğlu (CHP)",
        president_country: "Recep Tayyip Erdoğan",
        city_hall: { name: "İstanbul Büyükşehir Belediyesi", address: "Saraçhane, Atatürk Bulvarı 183, Fatih, Istanbul", tel: "+90 212 455-1300" },
        city_population: 15840000,
        happiness_rank: 98,
        religion: "Muslim 98% (Sunni majority), Christian/Jewish 2%",
        greeting: { hello: "Merhaba / Selam", thankyou: "Teşekkür ederim / Sağ ol", goodbye: "Hoşça kal / Güle güle", language: "Turkish" },
        tipping: "10-15% in restaurants. Not strictly mandatory but expected in tourist areas.",
        restaurant_closing: "Restaurants: 23:00-00:00. Meyhanes (taverns): late. Clubs: 04:00-06:00.",
        conduct_rules: ["Remove shoes at mosques — and cover head (women)", "Dress modestly at religious sites", "Bargaining is normal and expected in bazaars", "Tea is social glue — refuse is mild insult", "Do not insult Turkish state or Atatürk — legal risk"],
        top_food: ["Kebab (döner, şiş, adana)", "Meze (small dishes)", "Börek (pastry with cheese/meat)", "Baklava", "Menemen (eggs with tomato/pepper)", "Simit (sesame bread ring)"],
        top_drink: ["Çay (black tea in tulip glass — consumed constantly)", "Turkish coffee", "Ayran (yogurt drink)", "Raki (anise spirit)", "Pomegranate juice"],
        top_attraction: ["Hagia Sophia", "Topkapi Palace", "Grand Bazaar", "Blue Mosque", "Bosphorus cruise", "Galata Tower", "Basilica Cistern"],
        famous_company: ["Koç Holding", "Sabancı Holding", "Turkish Airlines", "Arçelik (Beko)", "Garanti BBVA"],
        sport_club: "Galatasaray / Fenerbahçe / Beşiktaş (Süper Lig — fierce rivals)",
        stadium: "Türk Telekom Stadium (Galatasaray, 52,652) / Ülker Stadium (Fenerbahçe, 50,530)",
        main_tv: "TRT 1 / Kanal D / Show TV",
        main_newspaper: "Hürriyet / Sabah / Milliyet",
        main_square: "Taksim Square (European side) / Sultanahmet Square (historic)",
        railway_station: { name: "Haydarpaşa (Asian side, historic) / Sirkeci (European side)", address: "Multiple terminal types" },
        drinking_water: "Technically safe but locals prefer bottled. Use bottled water.",
        public_transport: "İSTANBULKART — Metro, tram, funicular, ferry. Extremely complex but comprehensive. Ferry between continents is beautiful.",
        official_holiday: ["New Year", "National Sovereignty Day (Apr 23)", "Labour Day (May 1)", "Commemoration of Atatürk (May 19)", "Democracy Day (Jul 15)", "Victory Day (Aug 30)", "Republic Day (Oct 29)", "Eid Al Fitr (3 days)", "Eid Al Adha (4 days)"],
        scams: ["Shoe-shine scam — a man drops his brush near you, you pick it up, he 'thanks you' with a free shine then demands large payment", "Tea invitation scam — friendly local invites you for tea, the bill turns out to be enormous", "Taxi overcharge — use BiTaksi app or insist on meter; especially watch at Sabiha Gökçen airport", "Fake tour guides near Blue Mosque and Hagia Sophia — always hire from licensed agencies"],
    },

    "SG-singapore": {
        country: "SG",
        consulate: {
            en: { name: "U.S. Embassy Singapore", address: "27 Napier Road, Singapore 258508", tel: "+65 6476-9100" },
            de: { name: "Deutsche Botschaft Singapur", address: "25 Cairnhill Road, Singapore 229770", tel: "+65 6533-6002" },
            fr: { name: "Ambassade de France Singapour", address: "101-103 Cluny Park Road, Singapore 259595", tel: "+65 6880-7800" },
            hr: { name: "Embassy of Croatia Singapore (via Kuala Lumpur)", address: "Menara Tan & Tan, KL", tel: "+60 3 2164-3400" },
            it: { name: "Ambasciata d'Italia Singapore", address: "101 Thomson Road, United Square #27-02, Singapore 307591", tel: "+65 6250-6022" },
            es: { name: "Embajada de España Singapur", address: "7 Chatsworth Road, Singapore 249761", tel: "+65 6732-9788" },
            hi: { name: "High Commission of India Singapore", address: "31 Grange Road, Singapore 249570", tel: "+65 6737-6777" },
            ar: { name: "سفارة مصر في سنغافورة", address: "157 Clemenceau Avenue, Singapore 239427", tel: "+65 6737-1811" },
            zh: { name: "中国驻新加坡大使馆", address: "150 Tanglin Road, Singapore 247969", tel: "+65 6418-0100" },
            ja: { name: "在シンガポール日本国大使館", address: "16 Nassim Road, Singapore 258390", tel: "+65 6235-8855" },
        },
        hospital: { name: "Singapore General Hospital (SGH)", address: "Outram Rd, Singapore 169608", tel: "+65 6222-3322" },
        police_main: { name: "Singapore Police Force HQ", address: "391 New Bridge Road, Singapore 088762", tel: "999" },
        airport: { name: "Singapore Changi Airport (SIN) — world's best airport", iata: "SIN", distance: "20 km from city center", tel: "+65 6595-6868" },
        bank_exchange: { name: "DBS · OCBC · UOB · Mustafa Centre (24h exchange)", note: "Mustafa Centre in Little India — best exchange rates in Singapore, open 24/7." },
        pharmacy_24h: { name: "Guardian / Watsons (many 24h branches)", tel: "Check nearest branch" },
        dentist_24h: { name: "Q&M Dental (24h emergency)", tel: "+65 6337-7636" },
        vet_emergency: { name: "Mount Pleasant Veterinary Centre (24h)", address: "232 Whitley Road, Singapore 297824", tel: "+65 6252-0901" },
        taxi: { number: "ComfortDelGro: 6552-1111", app: "Grab (dominant — like Uber+food delivery)" },
        car_rental: { name: "Avis / Hertz / Budget", note: "Very expensive due to COE. Use MRT or Grab instead." },
        speed_limits: { urban: "50 km/h", expressway: "90 km/h" },
        no_go: ["Singapore is among the safest cities in the world — essentially no no-go zones", "Geylang area — legal red light district, otherwise fine"],
        special_zones: ["Orchard Road — shopping mile", "Marina Bay Sands area — entertainment/casino", "Sentosa Island — resort island (Universal Studios)", "Little India / Chinatown / Kampong Glam — cultural districts"],
        mayor: "Tharman Shanmugaratnam (President) / PM Lawrence Wong",
        president_country: "President Tharman Shanmugaratnam",
        city_hall: { name: "Singapore City Hall / The Istana (Presidential Palace)", address: "St Andrew's Road, Singapore 178957", tel: "+65 6332-8822" },
        city_population: 5918000,
        happiness_rank: 30,
        religion: "Buddhist 31%, Christian 19%, No religion 16%, Muslim 15%, Taoist 9%, Hindu 5%, Other 5%",
        greeting: { hello: "Hello / Hi / Oi (Singlish)", thankyou: "Thank you / Xie xie / Terima kasih", goodbye: "Bye / See you / Ciao (Singlish mix)", language: "English (official) + Mandarin + Malay + Tamil" },
        tipping: "Not customary — service charge 10% + GST 9% already added. Extra tipping not expected.",
        restaurant_closing: "Hawker centres: 24h (some). Restaurants: 22:00-23:00. Clubs: 03:00-04:00.",
        conduct_rules: ["NO chewing gum (import/sale illegal, fines)", "No smoking in almost all public places — heavy fines", "No eating/drinking on MRT — fine S$500", "Do not jaywalk — fined", "Drug trafficking — mandatory death penalty. Zero exceptions.", "LGBTQ+ laws liberalizing but still conservative socially"],
        top_food: ["Hainanese Chicken Rice (national dish)", "Laksa (spicy coconut noodle soup)", "Chilli Crab", "Char Kway Teow", "Satay", "Hokkien Mee", "Kaya toast breakfast"],
        top_drink: ["Tiger Beer (local)", "Teh tarik (pulled tea)", "Milo (hot chocolate)", "Fresh sugar cane juice"],
        top_attraction: ["Gardens by the Bay (Supertrees)", "Marina Bay Sands (infinity pool)", "Sentosa Island", "Singapore Zoo (night safari)", "Orchard Road", "Changi Jewel (airport waterfall)"],
        famous_company: ["Singapore Airlines", "DBS Bank", "Temasek Holdings", "CapitaLand", "Keppel Corp", "Grab (tech unicorn)"],
        sport_club: "Lion City Sailors / Singapore national football team",
        stadium: "Singapore Sports Hub — National Stadium (capacity 55,000)",
        main_tv: "Channel 5 (MediaCorp) / CNA (Channel NewsAsia)",
        main_newspaper: "The Straits Times / Today",
        main_square: "Marina Bay / Merlion Park / Orchard Road",
        railway_station: { name: "Singapore has no intercity trains — MRT only", address: "200+ MRT stations across 6 lines" },
        drinking_water: "Absolutely excellent — world's best tap water quality. Drink freely and abundantly.",
        public_transport: "MRT (Mass Rapid Transit) + buses. EZ-Link or NETS FlashPay card. Very punctual and clean.",
        official_holiday: ["New Year", "Chinese New Year (2 days)", "Good Friday", "Labour Day (May 1)", "Hari Raya Puasa", "Vesak Day", "Hari Raya Haji", "National Day (Aug 9)", "Deepavali", "Christmas"],
        scams: ["Illegal money changers offering too-good exchange rates — use licensed money changers (rates are regulated and posted)", "Fake discount tour packages at Chinatown — verify any tour operator with Singapore Tourism Board", "Overall very low crime and scam risk — Singapore has strict laws and enforcement"],
    },

    "US-sanfrancisco": {
        country: "US",
        consulate: {
            en: { name: "U.S. Department of State (Local Office)", address: "95 Hawthorne St, San Francisco, CA 94105", tel: "+1 415 744 4400" },
            de: { name: "Consulate General of the Federal Republic of Germany", address: "1960 Jackson St, San Francisco, CA 94109", tel: "+1 415 775 1061" },
            fr: { name: "Consulat Général de France", address: "44 Montgomery St #1000, San Francisco, CA 94104", tel: "+1 415 397 4300" },
            hr: { name: "Consulate General of the Republic of Croatia (Los Angeles - Accredited)", address: "11766 Wilshire Blvd, Los Angeles, CA 90025", tel: "+1 310 477 1009" },
            it: { name: "Consolato Generale d'Italia", address: "2590 Webster St, San Francisco, CA 94115", tel: "+1 415 292 9200" },
            es: { name: "Consulado General de España", address: "1405 Sutter St, San Francisco, CA 94109", tel: "+1 415 922 2995" },
            hi: { name: "Consulate General of India", address: "540 Arguello Blvd, San Francisco, CA 94118", tel: "+1 415 668 0662" },
            ar: { name: "Consulate General of the United Arab Emirates (Los Angeles - Accredited)", address: "1999 Avenue of the Stars, Los Angeles, CA 90067", tel: "+1 310 551 6500" },
            zh: { name: "中国驻旧金山总领事馆", address: "1450 Laguna St, San Francisco, CA 94115", tel: "+1 415 852 5900" },
            ja: { name: "在サンフランシスコ日本国総領事館", address: "275 Battery St #2100, San Francisco, CA 94111", tel: "+1 415 780 6000" },
        },
        hospital: { name: "Zuckerberg San Francisco General Hospital", address: "1001 Potrero Ave, San Francisco, CA 94110", tel: "+1 628 206 8000" },
        police_main: { name: "San Francisco Police Headquarters", address: "1245 3rd St, San Francisco, CA 94158", tel: "911" },
        airport: { name: "San Francisco International Airport (SFO)", iata: "SFO", distance: "21 km from city centre", tel: "+1 650 821 8211" },
        bank_exchange: { name: "Bank of America · Wells Fargo", note: "Cards are essential. Tap-to-pay is common. Many businesses are cashless." },
        pharmacy_24h: { name: "Walgreens (24h locations rotate)", address: "498 Castro St, San Francisco, CA 94114", tel: "+1 415 861 3136" },
        dentist_24h: { name: "San Francisco Dental Emergency Service", address: "1198 Post St, San Francisco, CA 94109", tel: "+1 415 771 2341" },
        vet_emergency: { name: "San Francisco Vets (24/7)", address: "2343 Fillmore St, San Francisco, CA 94115", tel: "+1 415 409 1840" },
        taxi: { number: "+1 415 333 3333", app: "Uber / Lyft / Flywheel" },
        car_rental: { name: "Hertz / Enterprise / Sixt", note: "Parking very expensive. Never leave valuables in sight — car break-ins ('smash and grabs') extremely frequent." },
        speed_limits: { urban: "40 km/h (25 mph)", highway: "100 km/h (60 mph)" },
        no_go: ["The Tenderloin — high concentration of drug use and homelessness; very sketchy day and night", "Sixth Street — known for violent crime and open-air drug markets, best avoided entirely", "Civic Center Plaza after dark — unsafe late at night"],
        special_zones: ["Golden Gate Bridge — no pedestrians at night (gates close)", "Alcatraz Island — strict ticket reservation required"],
        mayor: "Daniel Lurie (Independent/Democrat)",
        president_country: "Donald Trump (elected 2024)",
        city_hall: { name: "San Francisco City Hall", address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102", tel: "+1 415 554 4000" },
        city_population: 808000,
        happiness_rank: 19,
        religion: "No religion 46%, Christian 36%, Buddhist 6%, Jewish 4%, Other 8%",
        greeting: { hello: "Hi / Hey", thankyou: "Thanks / Thank you", goodbye: "Bye / Take care", language: "English" },
        tipping: "18-22% in restaurants standard. $1-2 per drink at bar. Tipping culture same as NYC.",
        restaurant_closing: "Restaurants: 22:00-23:00. Bars: 02:00. Many areas quiet after midnight.",
        conduct_rules: ["Cashless is normal — cards and phones accepted nearly everywhere", "Homeless population large — be respectful, do not photograph without consent", "Pronounced hills — driving requires hill-parking technique (curb wheels)"],
        top_food: ["Mission Burrito (huge, foil-wrapped)", "Sourdough Bread (Boudin Bakery since 1849)", "Dungeness Crab (Fisherman's Wharf)", "Cioppino (Italian-American seafood stew)", "Ghirardelli Chocolate"],
        top_drink: ["Anchor Steam Beer (local lager)", "Irish Coffee (The Buena Vista Cafe)", "Napa/Sonoma Valley Wines"],
        top_attraction: ["Golden Gate Bridge", "Alcatraz Island", "Fisherman's Wharf & Pier 39", "Lombard Street", "Painted Ladies (Alamo Square)", "Chinatown (oldest in North America)"],
        famous_company: ["Salesforce", "Uber", "Airbnb", "Twitter/X", "Stripe", "OpenAI"],
        sport_club: "San Francisco Giants (MLB) / Golden State Warriors (NBA)",
        stadium: "Oracle Park (41,265) / Chase Center (18,064)",
        main_tv: "KGO-TV (ABC) / KPIX (CBS) / KTVU (Fox)",
        main_newspaper: "San Francisco Chronicle",
        main_square: "Union Square",
        railway_station: { name: "Salesforce Transit Center / Caltrain Station", address: "4th St & King St" },
        drinking_water: "Safe and good quality from tap.",
        public_transport: "Muni (buses, light rail, cable cars) + BART (regional trains). Clipper card or mobile app. BART connects SFO to downtown in 30 min.",
        official_holiday: ["New Year", "MLK Day (Jan)", "Presidents Day (Feb)", "Memorial Day (May)", "Independence Day (Jul 4)", "Labor Day (Sep)", "Thanksgiving (Nov)", "Christmas"],
        scams: ["Broken Glasses Scam — someone bumps into you, drops broken glasses, aggressively demands money", "Fake tour operators near Fisherman's Wharf — unlicensed 'private boat tours' paid upfront, never materialize", "Buskers with pets used to solicit donations — sometimes organized groups"],
    },

};
