/* eslint-disable */
// CityDB — Sample Dataset (5 cities)
// Full dataset (100 cities): https://damc-979.github.io/citydb
// License: Mystudyglas@proton.me

var CITY_DB = {
    "DE-frankfurt": {
        country: "DE",
        consulate: {
            en: { name: "U.S. Consulate General Frankfurt", address: "Gießener Str. 30, 60435 Frankfurt", tel: "+49 69 7535-0" },
            de: { name: "Amerikanisches Generalkonsulat Frankfurt", address: "Gießener Str. 30, 60435 Frankfurt", tel: "+49 69 7535-0" },
            fr: { name: "Consulat Général des États-Unis Frankfurt", address: "Gießener Str. 30, 60435 Frankfurt", tel: "+49 69 7535-0" },
            hr: { name: "Konzulat Hrvatske u Frankfurtu", address: "Hoffmannstraße 1, 60528 Frankfurt", tel: "+49 69 677-7960" },
            it: { name: "Consolato Generale d'Italia Francoforte", address: "Kettenhofweg 61, 60325 Frankfurt", tel: "+49 69 753-900" },
            es: { name: "Consulado General de España Frankfurt", address: "Nibelungenallee 27, 60318 Frankfurt", tel: "+49 69 959-218-0" },
            hi: { name: "Indian Consulate General Frankfurt", address: "Friedrich-Ebert-Anlage 26, 60325 Frankfurt", tel: "+49 69 1530-050" },
            ar: { name: "القنصلية العامة لمصر في فرانكفورت", address: "Lyoner Str. 15, 60528 Frankfurt", tel: "+49 69 666-2966" },
            zh: { name: "中国驻法兰克福总领事馆", address: "Weißadlergasse 2-4, 60311 Frankfurt", tel: "+49 69 299-8820" },
            ja: { name: "在フランクフルト日本国総領事館", address: "Myliusstr. 34, 60323 Frankfurt", tel: "+49 69 238-1730" },
        },
        hospital: { name: "Universitätsklinikum Frankfurt", address: "Theodor-Stern-Kai 7, 60590 Frankfurt", tel: "+49 69 6301-0" },
        police_main: { name: "Polizeipräsidium Frankfurt", address: "Friedrich-Ebert-Anlage 11, 60327 Frankfurt", tel: "110" },
        airport: { name: "Frankfurt Airport (FRA)", iata: "FRA", distance: "12 km from city center", tel: "+49 180 6 372 4636" },
        bank_exchange: { name: "Deutsche Bank · Commerzbank · Reisebank at FRA", note: "Avoid airport exchange kiosks — rates poor. Use Deutsche Bank ATM." },
        pharmacy_24h: { name: "Apotheke im Hauptbahnhof", address: "Frankfurt Hbf, Level 1", tel: "+49 69 233-047" },
        dentist_24h: { name: "Zahnärztlicher Notfalldienst Frankfurt", tel: "116 117" },
        vet_emergency: { name: "Tierklinik Hofheim (24h)", address: "Katharina-Schlatter-Str. 15, Hofheim", tel: "+49 6192 9960-0" },
        taxi: { number: "069 230001", app: "mytaxi / FREE NOW" },
        car_rental: { name: "Sixt / Europcar / Hertz at FRA Airport and HBF", note: "Book online ahead — cheaper." },
        speed_limits: { urban: "50 km/h", rural: "100 km/h", autobahn: "No limit (advisory 130)" },
        no_go: ["Bahnhofsviertel (red light district) — fine by day, caution at night", "Konstablerwache at night — petty theft"],
        special_zones: ["Frankfurt Innenstadt — Low Emission Zone (Umweltzone), green sticker required", "Sachsenhausen — tourist friendly, busy weekend nights"],

        // IDENTITY & PEOPLE
        mayor: "Mike Josef (SPD)",
        president_country: "Frank-Walter Steinmeier",
        city_hall: { name: "Römer (Rathaus)", address: "Römerberg 23, 60311 Frankfurt", tel: "+49 69 212-0" },
        city_population: 764000,
        happiness_rank: 14, // Germany World Happiness Report 2024
        religion: "Christian 55%, Muslim 10%, No religion 28%, Other 7%",
        greeting: { hello: "Hallo / Guten Tag", thankyou: "Danke schön", goodbye: "Auf Wiedersehen", language: "German" },
        tipping: "Round up or 5-10% in restaurants. Not mandatory but appreciated.",
        restaurant_closing: "Restaurants: 22:00-23:00. Bars/clubs: 03:00-05:00",
        conduct_rules: ["Recycling is serious — use correct bins (Gelber Sack, Altpapier, Restmüll)", "Quiet hours (Ruhezeit): 13:00-15:00 and 22:00-07:00", "Jaywalking frowned upon", "Sunday: most shops closed"],

        // CULTURE & LIFESTYLE
        top_food: ["Grüne Soße (green herb sauce with boiled eggs)", "Handkäse mit Musik (sour milk cheese with onions)", "Frankfurter Würstchen (original)"],
        top_drink: ["Apfelwein (apple wine — Ebbelwoi)", "Hessen beer (Binding, Schöfferhofer)"],
        top_attraction: ["Römerberg (medieval old town)", "Städel Museum", "Palmengarten", "Goethe-Haus", "Sachsenhausen quarter"],
        famous_company: ["Deutsche Bank", "Commerzbank", "Lufthansa HQ", "DWS Group", "European Central Bank"],
        sport_club: "Eintracht Frankfurt (Bundesliga)",
        stadium: "Deutsche Bank Park (capacity 51,500)",
        main_tv: "HR Fernsehen (Hessischer Rundfunk)",
        main_newspaper: "Frankfurter Allgemeine Zeitung (FAZ)",
        main_square: "Römerberg",
        railway_station: { name: "Frankfurt Hauptbahnhof (Hbf)", address: "Am Hauptbahnhof 1" },
        drinking_water: "Tap water is excellent quality. Drink freely.",
        public_transport: "VGF (trams/metro) + S-Bahn. Get 24h ticket at machines.",
        official_holiday: ["New Year", "Good Friday", "Easter Monday", "Labour Day (May 1)", "German Unity Day (Oct 3)", "Christmas (Dec 25-26)"],
        scams: ["Pickpockets at Hauptbahnhof — keep bags in front on platforms and in the station", "Three-card monte at Hauptwache / Zeil — illegal street game, never engage", "Fake taxi touts at airport — use only official Taxi Frankfurt (yellow) from marked ranks", "Gold ring drop — stranger 'finds' a gold ring and offers to sell it to you"],
    },

    "HR-zagreb": {
        country: "HR",
        consulate: {
            en: { name: "U.S. Embassy Zagreb", address: "Ulica Thomasa Jeffersona 2, 10010 Zagreb", tel: "+385 1 661-2200" },
            de: { name: "Deutsche Botschaft Zagreb", address: "Ulica grada Vukovara 64, 10000 Zagreb", tel: "+385 1 630-0100" },
            fr: { name: "Ambassade de France Zagreb", address: "Hebrangova 2, 10000 Zagreb", tel: "+385 1 489-3600" },
            hr: { name: "Ministarstvo vanjskih poslova RH", address: "Trg Nikole Šubića Zrinskog 7-8, 10000 Zagreb", tel: "+385 1 456-9964" },
            it: { name: "Ambasciata d'Italia Zagabria", address: "Medulićeva 22, 10000 Zagreb", tel: "+385 1 489-4200" },
            es: { name: "Embajada de España Zagreb", address: "Tuškanac 21a, 10000 Zagreb", tel: "+385 1 481-7666" },
            hi: { name: "Embassy of India Zagreb", address: "Preradovićeva 21, 10000 Zagreb", tel: "+385 1 487-3269" },
            ar: { name: "سفارة مصر في زغرب", address: "Palmotićeva 28, 10000 Zagreb", tel: "+385 1 461-2680" },
            zh: { name: "中国驻克罗地亚大使馆", address: "Mlinovi 132, 10000 Zagreb", tel: "+385 1 463-2022" },
            ja: { name: "在クロアチア日本国大使館", address: "Miramarska 23, 10000 Zagreb", tel: "+385 1 486-3464" },
        },
        hospital: { name: "KBC Zagreb (University Hospital)", address: "Kišpatićeva 12, 10000 Zagreb", tel: "+385 1 238-8888" },
        police_main: { name: "Policijska uprava zagrebačka", address: "Petrinjska 30, 10000 Zagreb", tel: "192" },
        airport: { name: "Zagreb Airport (ZAG) — Franjo Tuđman", iata: "ZAG", distance: "17 km from city center", tel: "+385 1 626-5222" },
        bank_exchange: { name: "Croatia Banka · Erste Bank · Privredna banka (PBZ)", note: "ATMs widely available. EUR accepted in many places since Croatia joined Eurozone 2023." },
        pharmacy_24h: { name: "Gradska ljekarna Zagreb — Ilica 43", address: "Ilica 43, Zagreb", tel: "+385 1 484-8450" },
        dentist_24h: { name: "Dentalna poliklinika Zagreb", address: "Perkovčeva 3, Zagreb", tel: "+385 1 481-2004" },
        vet_emergency: { name: "Veterinarska stanica Zagreb (24h)", address: "Heinzelova 68, Zagreb", tel: "+385 1 619-3000" },
        taxi: { number: "060 800 800 (Radio Taxi Zagreb)", app: "Uber / Bolt available" },
        car_rental: { name: "Sixt / Budget / Europcar at ZAG Airport", note: "City center also has Hertz." },
        speed_limits: { urban: "50 km/h", rural: "90 km/h", highway: "130 km/h" },
        no_go: ["No major no-go zones — Zagreb is very safe", "Usual caution at night around Kvaternikov trg"],
        special_zones: ["Gornji Grad (Upper Town) — pedestrian area", "Jarun Lake — outdoor recreation zone"],

        mayor: "Tomislav Tomašević (Možemo!)",
        president_country: "Zoran Milanović",
        city_hall: { name: "Gradska skupština Zagreb", address: "Trg Stjepana Radića 1, 10000 Zagreb", tel: "+385 1 610-1000" },
        city_population: 767000,
        happiness_rank: 23,
        religion: "Catholic 86%, Orthodox 4%, Muslim 1%, Other 9%",
        greeting: { hello: "Dobar dan / Bok", thankyou: "Hvala", goodbye: "Doviđenja / Zbogom", language: "Croatian" },
        tipping: "Round up or 10% in restaurants. Not mandatory.",
        restaurant_closing: "Restaurants: 23:00. Cafes: 24:00. Clubs: 04:00-06:00",
        conduct_rules: ["Croatians are warm and hospitable", "Dress modestly when visiting churches", "Tap water is drinkable everywhere in Croatia"],
        top_food: ["Štrukli (cheese pastry)", "Roštilj (grilled meats)", "Fritule (small doughnuts)", "Purica s mlincima (turkey with pasta)"],
        top_drink: ["Rakija (fruit brandy)", "Ožujsko beer", "Karlovačko beer"],
        top_attraction: ["Gornji Grad (Upper Town)", "Cathedral of Zagreb", "Dolac Market", "Museum of Broken Relationships", "Jarun Lake"],
        famous_company: ["Rimac Automobili (electric hypercars)", "Infobip", "Span", "IN2 Group"],
        sport_club: "GNK Dinamo Zagreb (football)",
        stadium: "Stadion Maksimir (capacity 35,123)",
        main_tv: "HRT 1 (Hrvatska radiotelevizija)",
        main_newspaper: "Jutarnji list / Večernji list",
        main_square: "Trg bana Josipa Jelačića",
        railway_station: { name: "Zagreb Glavni kolodvor (Glavni kolodvor)", address: "Trg kralja Tomislava 12" },
        drinking_water: "Excellent. Zagreb tap water is among best in Europe.",
        public_transport: "ZET (trams + buses). Day ticket available at kiosks.",
        official_holiday: ["New Year", "Epiphany (Jan 6)", "Easter", "Labour Day (May 1)", "Corpus Christi", "Statehood Day (Jun 25)", "Homeland Thanksgiving Day (Aug 5)", "Assumption (Aug 15)", "All Saints (Nov 1)", "Christmas (Dec 25-26)"],
        scams: ["Unlicensed taxis — always use Radio Taxi 1717 or Uber", "Overcharging in Old Town restaurants — ask for a printed menu with prices before ordering", "Short-change trick at tourist spots — count your change carefully"],
    },

    "GB-london": {
        country: "GB",
        consulate: {
            en: { name: "Foreign & Commonwealth Office", address: "King Charles Street, London SW1A 2AH", tel: "+44 20 7008-5000" },
            de: { name: "Deutsche Botschaft London", address: "23 Belgrave Square, London SW1X 8PZ", tel: "+44 20 7824-1300" },
            fr: { name: "Ambassade de France Londres", address: "58 Knightsbridge, London SW1X 7JT", tel: "+44 20 7073-1000" },
            hr: { name: "Veleposlanstvo RH u Londonu", address: "21 Conway Street, London W1T 6BN", tel: "+44 20 7387-2022" },
            it: { name: "Ambasciata d'Italia Londra", address: "14 Three Kings Yard, London W1K 4EH", tel: "+44 20 7312-2200" },
            es: { name: "Embajada de España Londres", address: "39 Chesham Place, London SW1X 8SB", tel: "+44 20 7235-5555" },
            hi: { name: "High Commission of India London", address: "India House, Aldwych, London WC2B 4NA", tel: "+44 20 7836-8484" },
            ar: { name: "السفارة المصرية في لندن", address: "26 South Street, London W1K 1DW", tel: "+44 20 7499-3304" },
            zh: { name: "中国驻英国大使馆", address: "49-51 Portland Place, London W1B 1JL", tel: "+44 20 7299-4049" },
            ja: { name: "在英国日本国大使館", address: "101-104 Piccadilly, London W1J 7JT", tel: "+44 20 7465-6500" },
        },
        hospital: { name: "St Thomas' Hospital (NHS)", address: "Westminster Bridge Rd, London SE1 7EH", tel: "+44 20 7188-7188" },
        police_main: { name: "Metropolitan Police HQ", address: "New Scotland Yard, Victoria, London SW1H 0BG", tel: "999 (emergency) / 101 (non-emergency)" },
        airport: { name: "Heathrow Airport (LHR)", iata: "LHR", distance: "24 km from central London", tel: "+44 844 335-1801" },
        bank_exchange: { name: "Barclays · HSBC · NatWest", note: "Use ATMs. Avoid exchange bureaux at airports and tourist spots — terrible rates." },
        pharmacy_24h: { name: "Zafash Pharmacy (24h)", address: "233-235 Old Brompton Rd, London SW5 0EA", tel: "+44 20 7373-2798" },
        dentist_24h: { name: "Dental Emergency Helpline", tel: "111 (NHS)" },
        vet_emergency: { name: "PDSA Animal Hospital (24h)", address: "Various locations", tel: "+44 1923 412410" },
        taxi: { number: "0871 871 8710 (Black Cabs)", app: "Uber / Bolt / FREE NOW" },
        car_rental: { name: "Hertz / Sixt / Enterprise at LHR and city", note: "Left-hand traffic — be careful if not used to it." },
        speed_limits: { urban: "30 mph (48 km/h)", rural: "60 mph (96 km/h)", motorway: "70 mph (112 km/h)" },
        no_go: ["Peckham / Brixton at night — extra caution", "Whitechapel late night", "Anywhere — pickpockets on Tube, especially Central Line"],
        special_zones: ["ULEZ (Ultra Low Emission Zone) — entire Greater London, daily charge for old vehicles", "Congestion Charge Zone — Mon-Fri 07:00-18:00, Sat-Sun 12:00-18:00, £15/day", "Oxford Street — pedestrian priority"],

        mayor: "Sadiq Khan (Labour)",
        president_country: "King Charles III (Monarch) / Keir Starmer (PM)",
        city_hall: { name: "City Hall (London Assembly)", address: "Kamal Chunchie Way, London E16 1ZE", tel: "+44 20 7983-4000" },
        city_population: 9700000,
        happiness_rank: 17,
        religion: "Christian 46%, No religion 37%, Muslim 6%, Hindu 3%, Other 8%",
        greeting: { hello: "Hello / Hi", thankyou: "Thank you / Cheers", goodbye: "Goodbye / Cheers", language: "English" },
        tipping: "10-15% in restaurants. Not obligatory but expected in sit-down service.",
        restaurant_closing: "Restaurants: 23:00. Pubs: 00:00-01:00. Clubs: 03:00-06:00",
        conduct_rules: ["Queue — always, for everything. Jumping queues is deeply offensive", "Stand on the right on escalators — walk on left", "Keep voices low on public transport", "Oyster card or contactless for Tube — cash not accepted"],
        top_food: ["Fish and chips", "Full English breakfast", "Chicken tikka masala (national dish de facto)", "Pie and mash"],
        top_drink: ["Ale / bitter (pub culture)", "Tea — taken seriously", "Gin and tonic"],
        top_attraction: ["Big Ben / Houses of Parliament", "Tower of London", "British Museum", "Tate Modern", "Hyde Park", "Covent Garden"],
        famous_company: ["HSBC", "BP", "Shell", "Vodafone", "Rolls-Royce", "Barclays", "BBC"],
        sport_club: "Arsenal / Chelsea / Tottenham / West Ham (all Premier League)",
        stadium: "Wembley Stadium (capacity 90,000)",
        main_tv: "BBC One / ITV",
        main_newspaper: "The Guardian / The Times / Daily Mail",
        main_square: "Trafalgar Square",
        railway_station: { name: "London Waterloo / King's Cross / Paddington", address: "Multiple major terminals" },
        drinking_water: "Safe and good quality from tap. Slightly hard in London.",
        public_transport: "TfL — Tube, bus, Overground. Use Oyster or contactless. 24h Tube on weekends.",
        official_holiday: ["New Year", "Good Friday", "Easter Monday", "Early May Bank Holiday", "Spring Bank Holiday", "Summer Bank Holiday", "Christmas (Dec 25)", "Boxing Day (Dec 26)"],
        scams: ["Pickpockets on the Tube — especially Central and Jubilee lines at busy stations", "Fake police officers asking to inspect your wallet or passport — real police never do this", "Overpriced cycle rickshaws (pedicabs) near tourist areas — always agree price before riding", "Three-card trick teams at Oxford Street and Covent Garden — illegal, walk away", "Card skimming at standalone ATMs near tourist sites — use bank-branch ATMs only"],
    },

    "FR-paris": {
        country: "FR",
        consulate: {
            en: { name: "U.S. Embassy Paris", address: "2 Avenue Gabriel, 75008 Paris", tel: "+33 1 43-12-22-22" },
            de: { name: "Deutsche Botschaft Paris", address: "13 Avenue Franklin D. Roosevelt, 75008 Paris", tel: "+33 1 53-83-45-00" },
            fr: { name: "Ministère des Affaires étrangères", address: "37 Quai d'Orsay, 75007 Paris", tel: "+33 1 43-17-67-67" },
            hr: { name: "Veleposlanstvo RH u Parizu", address: "39 Boulevard Malesherbes, 75008 Paris", tel: "+33 1 53-04-55-00" },
            it: { name: "Ambasciata d'Italia Parigi", address: "47 Rue de Varenne, 75007 Paris", tel: "+33 1 49-54-03-00" },
            es: { name: "Embajada de España París", address: "22 Avenue Marceau, 75008 Paris", tel: "+33 1 44-43-18-00" },
            hi: { name: "Embassy of India Paris", address: "15 Rue Alfred Dehodencq, 75016 Paris", tel: "+33 1 40-50-70-70" },
            ar: { name: "السفارة المصرية في باريس", address: "56 Avenue d'Iéna, 75116 Paris", tel: "+33 1 53-67-88-30" },
            zh: { name: "中国驻法国大使馆", address: "11 Avenue George V, 75008 Paris", tel: "+33 1 47-23-36-77" },
            ja: { name: "在フランス日本国大使館", address: "7 Avenue Hoche, 75008 Paris", tel: "+33 1 48-88-62-00" },
        },
        hospital: { name: "Hôpital Hôtel-Dieu (AP-HP)", address: "1 Parvis Notre-Dame, 75004 Paris", tel: "+33 1 42-34-82-34" },
        police_main: { name: "Préfecture de Police de Paris", address: "9 Boulevard du Palais, 75004 Paris", tel: "17" },
        airport: { name: "Charles de Gaulle Airport (CDG)", iata: "CDG", distance: "25 km from city center", tel: "+33 1 70-36-39-50" },
        bank_exchange: { name: "BNP Paribas · Société Générale · Crédit Agricole", note: "Use bank ATMs. Change bureaux near Champs-Élysées — very poor rates." },
        pharmacy_24h: { name: "Pharmacie des Champs (24h)", address: "84 Avenue des Champs-Élysées, 75008 Paris", tel: "+33 1 45-62-02-41" },
        dentist_24h: { name: "SOS Dentaire", tel: "+33 1 43-37-51-00" },
        vet_emergency: { name: "ADVETIA Clinique Vétérinaire (24h)", address: "9 Rue Beaubourg, 75004 Paris", tel: "+33 1 71-19-74-74" },
        taxi: { number: "3609 (G7 Taxis)", app: "Uber / Bolt / Heetch" },
        car_rental: { name: "Hertz / Europcar / ADA at CDG and city", note: "Paris traffic is intense. Metro usually faster." },
        speed_limits: { urban: "30 km/h (most streets since 2021)", peripheral: "70 km/h", highway: "130 km/h" },
        no_go: ["Gare du Nord surroundings — pickpockets, scammers", "Barbès-Rochechouart at night", "Bois de Boulogne at night", "Stade de France area at night"],
        special_zones: ["Zone à Faibles Émissions (ZFE) — low emission zone entire Paris", "Paris Plages — summer beach along Seine", "Marais — LGBTQ+ friendly, tourist popular"],

        mayor: "Anne Hidalgo (PS)",
        president_country: "Emmanuel Macron",
        city_hall: { name: "Hôtel de Ville de Paris", address: "Place de l'Hôtel-de-Ville, 75004 Paris", tel: "+33 1 42-76-40-40" },
        city_population: 2200000,
        happiness_rank: 21,
        religion: "Christian 51%, No religion 35%, Muslim 10%, Jewish 1%, Other 3%",
        greeting: { hello: "Bonjour / Bonsoir", thankyou: "Merci / Merci beaucoup", goodbye: "Au revoir / Bonne journée", language: "French" },
        tipping: "Service included by law (15%). Extra tip appreciated but not expected — round up or leave €1-2.",
        restaurant_closing: "Restaurants: 22:30-23:00. Brasseries: 01:00. Clubs: 06:00-08:00",
        conduct_rules: ["Always say Bonjour/Bonsoir when entering a shop — mandatory politeness", "Bread is not ordered — brought automatically", "Do not eat while walking — considered rude", "Dress well — Parisians notice"],
        top_food: ["Croissant (fresh from boulangerie)", "Steak frites", "Croque-monsieur", "Escargots", "Crème brûlée"],
        top_drink: ["Wine (Bordeaux, Burgundy, Champagne)", "Pastis", "Café express"],
        top_attraction: ["Eiffel Tower", "Louvre Museum", "Notre-Dame Cathedral", "Musée d'Orsay", "Sacré-Cœur", "Palace of Versailles (30km)"],
        famous_company: ["Louis Vuitton (LVMH)", "L'Oréal", "Total Energies", "BNP Paribas", "Airbus", "Dior", "Chanel"],
        sport_club: "Paris Saint-Germain (PSG)",
        stadium: "Parc des Princes (capacity 47,929)",
        main_tv: "TF1 / France 2",
        main_newspaper: "Le Monde / Le Figaro / Libération",
        main_square: "Place de la Concorde / Place de la République",
        railway_station: { name: "Gare du Nord / Gare de Lyon / Gare Saint-Lazare", address: "Multiple major terminals" },
        drinking_water: "Safe from tap. Slightly chlorinated taste. Free drinking fountains throughout city.",
        public_transport: "RATP — Métro, RER, bus. Navigo card or t+ tickets. Very extensive network.",
        official_holiday: ["New Year", "Easter Monday", "Labour Day (May 1)", "Victory in Europe Day (May 8)", "Ascension", "Bastille Day (Jul 14)", "Assumption (Aug 15)", "All Saints (Nov 1)", "Armistice Day (Nov 11)", "Christmas"],
        scams: ["Friendship bracelet scam at Sacré-Cœur — vendors forcibly tie a bracelet on your wrist then demand payment", "Gold ring drop scam near Eiffel Tower — 'found' gold ring offered for sale", "Petition clipboard scam — someone asks you to sign a petition then demands money", "Pickpockets on Métro Line 1 and RER B (CDG airport line) — keep bags in front", "Fake airport shuttle drivers at CDG — use only official RATP buses or licensed taxis"],
    },

    "JP-tokyo": {
        country: "JP",
        consulate: {
            en: { name: "U.S. Embassy Tokyo", address: "1-10-5 Akasaka, Minato, Tokyo 107-8420", tel: "+81 3 3224-5000" },
            de: { name: "Deutsche Botschaft Tokio", address: "4-5-10 Minami-Azabu, Minato, Tokyo 106-0047", tel: "+81 3 5791-7700" },
            fr: { name: "Ambassade de France Tokyo", address: "4-11-44 Minami-Azabu, Minato, Tokyo 106-8514", tel: "+81 3 5798-6000" },
            hr: { name: "Embassy of Croatia Tokyo", address: "3-3-10 Hiroo, Shibuya, Tokyo 150-0012", tel: "+81 3 5464-2400" },
            it: { name: "Ambasciata d'Italia Tokyo", address: "2-5-4 Mita, Minato, Tokyo 108-8302", tel: "+81 3 3453-5291" },
            es: { name: "Embajada de España Tokio", address: "1-3-29 Roppongi, Minato, Tokyo 106-0032", tel: "+81 3 3583-8531" },
            hi: { name: "Embassy of India Tokyo", address: "2-2-11 Kudan Minami, Chiyoda, Tokyo 102-0074", tel: "+81 3 3262-2391" },
            ar: { name: "سفارة مصر في طوكيو", address: "1-5-4 Aobadai, Meguro, Tokyo 153-0042", tel: "+81 3 3770-8022" },
            zh: { name: "中国驻日本大使馆", address: "3-4-33 Moto-Azabu, Minato, Tokyo 106-0046", tel: "+81 3 3403-3380" },
            ja: { name: "外務省（在外公館）", address: "2-2-1 Kasumigaseki, Chiyoda, Tokyo 100-8919", tel: "+81 3 3580-3311" },
        },
        hospital: { name: "Tokyo Medical and Surgical Clinic", address: "32 Shiba Koen 3-chome, Minato, Tokyo 105-0011", tel: "+81 3 3436-3028" },
        police_main: { name: "Metropolitan Police Department", address: "2-1-1 Kasumigaseki, Chiyoda, Tokyo 100-8929", tel: "110" },
        airport: { name: "Narita International Airport (NRT)", iata: "NRT", distance: "60 km from city center", tel: "+81 476 34-8000" },
        bank_exchange: { name: "Japan Post Bank · 7-Eleven ATMs · Shinsei Bank", note: "7-Eleven and Japan Post ATMs accept foreign cards. Most places cash only." },
        pharmacy_24h: { name: "Matsumoto Kiyoshi (major chain, many 24h locations)", tel: "Check nearest branch" },
        dentist_24h: { name: "Tokyo Dental Emergency Tel", tel: "+81 3 3263-2389" },
        vet_emergency: { name: "Japan Animal Referral Medical Center (24h)", address: "2-12-24 Yanagishima, Kawasaki", tel: "+81 44 712-0916" },
        taxi: { number: "03-3563-5101 (Nihon Kotsu)", app: "GO app / DiDi" },
        car_rental: { name: "Toyota Rent a Car / Times Car Rental", note: "International license required. Left-hand traffic." },
        speed_limits: { urban: "40-60 km/h", expressway: "80-100 km/h" },
        no_go: ["Tokyo is extremely safe — almost no no-go zones", "Kabukicho (Shinjuku) — entertainment district, minor scam risk at night"],
        special_zones: ["Shibuya — pedestrian scramble crossing (world famous)", "Akihabara — electronics/anime district", "Harajuku — fashion youth culture"],

        mayor: "Yuriko Koike (Governor of Tokyo)",
        president_country: "Emperor Naruhito / PM Fumio Kishida",
        city_hall: { name: "Tokyo Metropolitan Government Building", address: "2-8-1 Nishi-Shinjuku, Shinjuku, Tokyo 163-8001", tel: "+81 3 5321-1111" },
        city_population: 13960000,
        happiness_rank: 47,
        religion: "Shinto + Buddhist 70% (often both), Christian 1%, Other/None 29%",
        greeting: { hello: "Konnichiwa (こんにちは)", thankyou: "Arigatou gozaimasu (ありがとうございます)", goodbye: "Sayonara (さようなら)", language: "Japanese" },
        tipping: "NEVER tip in Japan — considered rude or offensive. Service is always included.",
        restaurant_closing: "Restaurants: 22:00-23:00. Izakayas: 00:00-02:00. Last trains ~01:00.",
        conduct_rules: ["No eating or drinking while walking", "Speak quietly on trains — silent culture", "Two hands when giving or receiving business cards", "Remove shoes when entering homes and many traditional venues", "Cash is king — many places do not accept cards"],
        top_food: ["Sushi / Sashimi", "Ramen", "Tempura", "Yakitori", "Wagyu beef", "Onigiri"],
        top_drink: ["Sake (rice wine)", "Japanese whisky (Suntory, Nikka)", "Matcha", "Asahi/Sapporo/Kirin beer"],
        top_attraction: ["Shibuya crossing", "Senso-ji Temple (Asakusa)", "Shinjuku Gyoen", "teamLab digital art", "Tokyo Skytree", "Harajuku"],
        famous_company: ["Toyota", "Sony", "Honda", "Panasonic", "Mitsubishi", "Softbank", "Uniqlo"],
        sport_club: "FC Tokyo / Urawa Red Diamonds (J-League)",
        stadium: "Japan National Stadium (capacity 68,000)",
        main_tv: "NHK / Fuji TV",
        main_newspaper: "Yomiuri Shimbun / Asahi Shimbun",
        main_square: "Shibuya Scramble / Shinjuku Station area",
        railway_station: { name: "Tokyo Station / Shinjuku Station (busiest in world)", address: "1 Chome-9 Marunouchi, Chiyoda" },
        drinking_water: "Excellent — tap water is among the best in the world. Drink freely.",
        public_transport: "JR East + Tokyo Metro + Toei. IC card (Suica/Pasmo) essential. Extremely punctual.",
        official_holiday: ["New Year (Jan 1-3)", "Coming of Age Day", "National Foundation Day (Feb 11)", "Spring Equinox", "Showa Day (Apr 29)", "Golden Week (late Apr-May 5)", "Marine Day", "Mountain Day", "Respect for Aged Day", "Autumn Equinox", "Health & Sports Day", "Culture Day (Nov 3)", "Labour Day (Nov 23)", "Emperor's Birthday (Feb 23)"],
        scams: ["Tourist trap bars in Roppongi — extremely overpriced drinks and aggressive staff, agree all prices before ordering", "Rigged games near Shinjuku station — 'lucky' draw games are impossible to win", "Taxi overcharge for tourists — always use metered official taxis or apps like GO"],
    },
};
